#!/usr/bin/env bash
#
# ha-rules-import.sh -- emit OpenTofu import blocks for the HA rules that a
# Proxmox 8 -> 9 upgrade produced.
#
# Upgrading converts every HA group into a node-affinity rule, but the rule is
# given a generated identifier -- "ha-rule-6e12c05d-c269" and the like -- and
# the group's name survives only in the comment.  Those identifiers are minted
# during the upgrade, so they differ between clusters: the ones from a
# rehearsal on a test cluster will not be the ones production gets.  Import
# blocks therefore cannot be written ahead of time; they have to be generated
# from the cluster after it has been upgraded, which is what this does.
#
# Usage:
#   export PVE=https://node.example.org:8006/api2/json
#   export PVE_TOKEN='root@pam!tofu=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx'
#   ./ha-rules-import.sh > imports.tf
#
# or with a ticket instead of a token:
#   export PVE_TICKET="$(curl -sSk -d username=root@pam \
#       --data-urlencode "password=${PVE_PASS}" "${PVE}/access/ticket" \
#       | jq -r .data.ticket)"
#
set -euo pipefail

: "${PVE:?set PVE to the API base, e.g. https://node:8006/api2/json}"

auth=()
if [ -n "${PVE_TOKEN:-}" ]; then
    auth=(-H "Authorization: PVEAPIToken=${PVE_TOKEN}")
elif [ -n "${PVE_TICKET:-}" ]; then
    auth=(-H "Cookie: PVEAuthCookie=${PVE_TICKET}")
else
    echo "set PVE_TOKEN or PVE_TICKET" >&2
    exit 2
fi

command -v jq >/dev/null || { echo "jq is required" >&2; exit 1; }

rules=$(curl -sSk "${auth[@]}" "${PVE}/cluster/ha/rules")
echo "$rules" | jq -e '.data' >/dev/null 2>&1 || {
    echo "unexpected response from ${PVE}/cluster/ha/rules:" >&2
    echo "$rules" >&2
    exit 1
}

count=$(echo "$rules" | jq '.data | length')
if [ "$count" = 0 ]; then
    echo "# no HA rules found -- has the cluster been upgraded to Proxmox 9 yet?" >&2
    exit 0
fi

echo "# Generated by ha-rules-import.sh on $(date -u +%FT%TZ)"
echo "# Rule identifiers are cluster specific: regenerate this rather than"
echo "# copying it between clusters."
echo

echo "$rules" | jq -r '
  .data[]
  | . as $r
  # The terraform resource name comes from the comment, which is where the
  # pre-upgrade HA group name ended up.  Fall back to the generated id when a
  # rule has no comment, so nothing is silently dropped.
  | (($r.comment // $r.rule)
     | ascii_downcase
     | gsub("[^a-z0-9]+"; "_")
     | gsub("^_+|_+$"; "")) as $name
  | "# was HA group: \($r.comment // "(no comment)")   type: \($r.type)\n"
  + "#   resources: \($r.resources // "-")\n"
  + "#   nodes:     \($r.nodes // "-")\n"
  + "import {\n  to = proxmox_ha_rule.\($name)\n  id = \"\($r.rule)\"\n}\n"
'

echo "# Next: run 'tofu plan -generate-config-out=ha_rules.tf' to have OpenTofu"
echo "# write matching resource blocks, then review them before applying."
